project:
  type: website
  output-dir: _build
  title: "Artificial Intelligence Summer School - CUNEF Universidad"
  render:
    - "*.qmd"
    - "!*.ipynb"

format:
  html:
    theme: cosmo
    toc: true


website:
  title: "AI Summer School - CUNEF Universidad"
  favicon: templates/images/cunef.png
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Python Basics"
        href: tutorial/python.html
      - text: "Numpy"
        href: tutorial/numpy.html
      - text: "Pandas"
        href: tutorial/pandas.html
      - text: "Scikit-learn"
        href: tutorial/sklearn.html


  page-footer:
    left: |
      ![](/templates/images/cunef.png){width=50%}
