# UPPER PROJECT CONFIGURATION
project:
    type: website
    output-dir: _build

    title: "Aprendizaje Automático - Ciencia de Datos"

    resources:
        - resources
        - templates

    render:
        - "resources/AA_00_quarto_intro.qmd"
        - "*.qmd"
        - "!*.ipynb"

format:
    html:
        theme: zephyr
        toc: true


website:
    title: "Aprendizaje Automático - Ciencia de Datos"
    favicon: templates/images/cunef.png
    navbar:
        left:
            - text: "Aprendizaje Automático"
              href: index.html
            - text: "Aprendizaje Automático - Predicción"
              href: aap/aap.html
            - text: "Aprendizaje Automático - Clasificación"
              href: aac/aac.html
    page-navigation: true

    page-footer:
        left: |
            ![](/templates/images/cunef.png){width=50%}
