name: Render Quarto files, validate and upload preview site

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# cancel stale runs when the PR is updated
concurrency:
  group: "pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: true


jobs:
  render-preview:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      # Download the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install ubuntu dependencies
      - name: Install ubuntu dependencies
        run: |
          sudo apt update
          sudo apt -y install \
            curl \
            libmagick++-dev \
            libcurl4-openssl-dev \
            libpng-dev \
            libpoppler-cpp-dev

      # Python dependencies
      - name: Install python dependencies
        run: |
          sudo apt-get install -y \
            python3 \
            python3-pip

      # TODO: add a requirements.txt file
      # Install python packages
      - name: Install python packages
        run: |
          pip install \
            numpy \
            matplotlib \
            pandas \
            seaborn \
            scikit-learn \
            nbformat \
            jupyter \
            jupyter-cache

      # Install Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      # Render Quarto files
      - name: Render Quarto files
        run: |
          quarto render --output-dir _build

      # Run Quarto sanity check
      - name: Link & HTML sanity check
        run: quarto check

      # Store the result as artifact
      - name: Store the result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-site
          path: _build
